### ISSUE TITLE
Use template-literal instead of EJS

### ISSUE THREAD

**Issue by Drulac** [fenwick67/bumbler#8]
[Template Literal](https://github.com/Drulac/template-literal) is fastest, smallest and simplest template engine, because it use JS's literal template feature.

It's  55 times faster than EJS, and it also use less CPU and RAM ressources, so it may be a good idea to use it instead of EJS 😀

**Comment by fenwick67** [comment]
Do you have benchmarks against Pug (formerly Jade) templates?

**Comment by Drulac** [comment]
No, but it's a good idea, I will add it soon :-)

**Comment by Drulac** [comment]
Pug is about 900 times slower at compilation and 4 times slower in render 😅 !

**Comment by fenwick67** [comment]
Compilation I'm not worried about, since it's only done once per full site build.  If rendering were *orders of magnitude* faster then I would consider it, but I'll take Pug's terse syntax over a rendering speedup.
